Project.MVCUI/Areas/SuperAdmin/Models/ViewModels/RoleVM.cs
using System.ComponentModel.DataAnnotations;

namespace Project.MVCUI.Areas.SuperAdmin.Models.ViewModels
{
    public class RoleVM
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Rol adı boş geçilemez !")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Rol açıklaması boş geçilemez !")] 
        public string Role_Exp { get; set; }
    }
}

Project.MVCUI/Models/ErrorViewModel.cs
namespace Project.MVCUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Project.MVCUI/Areas/SuperAdmin/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace Project.MVCUI.Areas.SuperAdmin.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Project.MVCUI/Areas/SuperAdmin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Project.BLL.Manager_Services.Abstracts;
using Project.Entities.Models;
using Project.MVCUI.Areas.SuperAdmin.Models.ViewModels;

namespace Project.MVCUI.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin")]
    public class RoleController : Controller
    {
        private readonly IRole_Manager _manager;

        private readonly RoleManager<Role> _roleManager;

        public RoleController(IRole_Manager manager, RoleManager<Role> roleManager)
        {
            _roleManager = roleManager;
            _manager = manager;
        }

        //List
        public IActionResult Index()
        {
            var roles = _manager.GetActives();
            return View(roles);
        }

        //Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RoleVM role)
        {
            if(ModelState.IsValid)
            {
                Role _role=new Role();
                _role.Name = role.Name;
                _role.Role_Exp = role.Role_Exp;

                var result = await _roleManager.CreateAsync(_role);

                if (result.Succeeded)
                {
                    TempData["SuccessMessage"] = "Kullanıcı Rolü Başarıyla Oluşturuldu !";

                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ExtTypeName"] = "Bu rol zaten mevcut !";
                    return View(role);
                }
            }
            return View(role);
        }
        //Update

        public IActionResult Update(int id)
        {
            var role = _manager.Find(id);
            RoleVM _role = new RoleVM();
            _role.Id = id;
            _role.Name = role.Name;
            _role.Role_Exp= role.Role_Exp;
            return View(_role);
        }

        [HttpPost]

        public IActionResult Update(RoleVM role) 
        {
            if (ModelState.IsValid)
            {
                Role _role=new Role();
                _role.Id= role.Id;
                _role.ID=role.Id;
                _role.Name=role.Name;
                _role.Role_Exp=role.Role_Exp;

                var roles=_manager.GetActives();

                foreach(var i in roles)
                {
                    if(i.Name==_role.Name && i.Id!=role.Id) 
                    {
                        TempData["ExtTypName"] = "Bu rol zaten mevcut";
                        return View(role);
                    }
                }
                _manager.Update(_role);
                TempData["UpdateMessage"] = "Rol kaydı başarıyla güncellendi !";
                return RedirectToAction("Index");
            }
            return View(role);
        }
        //Delete
        [HttpGet]
        public IActionResult Delete(int id) 
        {
            var data=_manager.Find(id);
            _manager.Delete(data);
            return RedirectToAction("Index");   
        }


    }
}

Project.MVCUI/Areas/SuperAdmin/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Project.BLL.Manager_Services.Abstracts;
using Project.Entities.Models;

namespace Project.MVCUI.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin")]
    public class UserController : Controller
    {
        private readonly IUser_Manager _custom_user_manager;
        private readonly UserManager<User> _usermanager;

        public UserController(IUser_Manager custom_user_manager, UserManager<User> usermanager)
        {
            _custom_user_manager = custom_user_manager;
            _usermanager = usermanager;
        }

        //List

        public IActionResult Index()
        {
            var users = _custom_user_manager.GetActives();

            return View(users);
        }
    }
}

Project.MVCUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Project.MVCUI.Models;
using System.Diagnostics;

namespace Project.MVCUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Project.MVCUI/Areas/SuperAdmin/Views/Admin/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Project.MVCUI/Areas/SuperAdmin/Views/Role/Create.cshtml
@using Project.MVCUI.Areas.SuperAdmin.Models.ViewModels;
@model RoleVM;

<link href="~/css/CenterDiv.css" rel="stylesheet" />

<div class="container">
    <div class="centered-div">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Yeni Kullanıcı Rolü Oluşturma</h3>
            </div>
            <form method="post">
                <div class="card-body">
                    <div class="form-group">
                        <label>Rol Adı</label>
                        <input id="myInput" autocomplete="off" asp-for="Name" type="text" class="form-control" placeholder="Rol Adı">
                        <span style="color:red" asp-validation-for="Name"></span>
                        @if (TempData["ExtTypeName"] != null)
                        {
                            <span style="color:red">@TempData["ExtTypeName"]</span>
                        }
                    </div>
                    <div class="form-group">
                        <label>Rol Açıklaması</label>
                        <input id="myInput" autocomplete="off" asp-for="Role_Exp" type="text" class="form-control" placeholder="Rol Açıklaması">
                        <span style="color:red" asp-validation-for="Role_Exp"></span>
                    </div>
                </div>
                <div class="card-footer">
                    <button onclick="checkInput()" type="submit" class="btn btn-primary">Kullanıcı Rolü Oluştur</button>
                    <button asp-area="SuperAdmin" asp-controller="Role" asp-action="Index" class="btn btn-primary" style="float:right">Geri</button>
                </div>
            </form>
        </div>
    </div>
</div>

Project.MVCUI/Areas/SuperAdmin/Views/Role/Index.cshtml
@using Project.Entities.Models;
@model List<Role>;
<style>
    body{
        padding: 30px;
    }
</style>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Kullanıcı Görevleri</h3>
                    <a asp-area="SuperAdmin" asp-controller="Role" asp-action="Create" class="btn btn-primary" style="float: right;">Yeni Kullanıcı Rolü Oluştur</a>
                </div>
                <div class="card-body table-responsive p-0">
                    <table class="table-bordered" id="dataTableData">
                        <thead>
                            <tr>
                                <th class="cm-strong">Rol Adı</th>
                                <th class="cm-strong">Rol Açıklaması</th>
                                <td style="text-align:center;" class="cm-strong">İşlemler</td>
                            </tr>
                        </thead>
                        <tbody>
                            
                                @if (Model.Count > 0)
                                {
                                    foreach (var role in Model)
                                    {
                                        <tr>
                                            <td>@role.Name</td>
                                            <td>@role.Role_Exp</td>
                                            <td style="text-align:center;">
                                                <a asp-area="SuperAdmin" asp-controller="Role" asp-action="Update" asp-route-id="@role.Id" class="btn btn-xs btn-warning">Güncelle</a>
                                            @if(role.Name  != "SuperAdmin")
                                            {
                                                <button class="btn btn-xs btn-danger delete" id="@role.Id" name="@role.Name">Sil</button>
                                            }
                                            </td>
                                        </tr>
                                    }
                                }
                            

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- SweetAlert Delete Button -->

@section scripts{
    <script>
        var name;
        var id;
        $(".delete").on("click", function () {
            id=$(this).attr('id');
            name=$(this).attr('name');
            displayAlert();
        })
        function displayAlert(){
            Swal.fire({
                title: 'Emin Misiniz ?',
                text: `${name} İsimli Rol Silinecek.`,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Vazgeç',
                confirmButtonText: 'Evet, Sil!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: `/SuperAdmin/Role/Delete/${id}`,
                        type: 'get',
                        success: function (data) {
                            Swal.fire(
                                'Silindi!',
                                'Rol Kaydı Basariyla Silindi.',
                                'success'
                            ).then((result) => {
                                if(result.isConfirmed){
                                    location.reload();
                                }
                            })
                        }
                    })
                }
            })
        }
    </script>
    
    @if (TempData["SuccessMessage"] != null)
    {
        <script>
            document.addEventListener('DOMContentLoaded', function(){
                Swal.fire({
                    title: 'Oluşturuldu !',
                    text: 'Rol Kaydı Başarıyla Oluşturuldu !',
                    icon: 'success'
                });
            });
        </script>   
    }

    @if (TempData["UpdateMessage"] != null)
    {
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                Swal.fire({
                    title: 'Güncellendi !',
                    text: 'Rol Kaydı Başarıyla Güncellendi !',
                    icon: 'success'
                });
            });
        </script>
    }
}

Project.MVCUI/Areas/SuperAdmin/Views/Role/Update.cshtml
@using Project.MVCUI.Areas.SuperAdmin.Models.ViewModels;
@model RoleVM

<link href="~/css/CenterDiv.css" rel="stylesheet" type="text/css" />

<div class="container">
    <div class="centered-div">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Kullanıcı Rolü Güncelleme Ekranı</h3>
            </div>
            <form method="post">
                <div class="card-body">
                    <div class="form-group">
                        <label class="col-md-3">Rol Adı</label>
                        <input autocomplete="off" asp-for="Name" type="text" class="form-control" value="@Model.Name" placeholder="@Model.Name">
                        <span style="color:red" asp-validation-for="Name"></span>
                        @if (TempData["ExtTypeName"] != null)
                        {
                            <span style="color:red">@TempData["ExtTypeName"]</span>
                        }
                    </div>
                    <div class="form-group">
                        <label class="col-md-3">Rol Açıklaması</label>
                        <input autocomplete="off" asp-for="Role_Exp" type="text" class="form-control" value="@Model.Role_Exp" placeholder="@Model.Role_Exp">
                        <span style="color:red" asp-validation-for="Role_Exp"></span>
                    </div>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Kullanıcı Rolünü Güncelle</button>
                    <button asp-area="SuperAdmin" asp-controller="Role" asp-action="Index" class="btn btn-primary" style="float:right">Geri</button>
                </div>
            </form>
        </div>
    </div>
</div>

Project.MVCUI/Areas/SuperAdmin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Identity;
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Mita Enerji</title>
  <link rel="icon" href="~/images/mita-logok.ico" type="image/x-icon" >
  <!--DataTables-->
  <link href="~/css/datatablecss/datatables.min.css" rel="stylesheet" />
  <link href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css" rel="stylesheet">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="~/css/all.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="~/css/OverlayScrollbars.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="~/css/adminlte.min.css">
</head>
<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Ana Sayfa</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>
      @* Buttons *@
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fa-solid fa-house"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a asp-action="Index" class="brand-link">
      <img src="~/images/mita-logo.png" alt="AdminLTE Logo" style="opacity: .8" height="30" width="230">
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      @if (User.Identity.Name != null)
      {
          <div class="user-panel mt-3 pb-3 mb-3 d-flex">

              <div class="info">
                  <a asp-area="SuperAdmin" asp-controller="Home" asp-action="Index" class="d-block">@User.Identity.Name</a>
              </div>
          </div>
      }

      <!-- SidebarSearch Form -->
      <div class="form-inline" style="margin-top:15px">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item">
                <a asp-area="SuperAdmin" asp-controller="Home" asp-action="Index" class="nav-link">
                    <i class="nav-icon fas fa-home"></i>
                    <p>
                        Yönetim Paneli
                    </p>
                </a>
            </li>

            <!-- Sistem Tanımları -->

            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-bars"></i>
                    <p>
                        Sistem Tanımları
                        <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav-treeview">
                    <li>
                        <a asp-area="SuperAdmin" asp-controller="User" asp-action="Index" class="nav-link">
                            <i class="fas fa-user nav-icon"></i>
                            <p>Kullanıcı İşlemleri</p>
                        </a>
                    </li>
                </ul>

                <ul class="nav-treeview">
                    <li>
                        <a asp-area="SuperAdmin" asp-controller="Role" asp-action="Index" class="nav-link">
                            <i class="fas fa-users nav-icon"></i>
                            <p>Kullanıcı Rol İşlemleri</p>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
          @RenderBody()
    </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <strong>Copyright &copy; ECG and HEG</strong>
    All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- For Treeview -->
<script>
    $(document).ready(function () {
        var url = window.location;

        $('ul.nav-sidebar a').filter(function () {

            if (this.href) {

                return this.href == url;

            }

        }).addClass('active').parents('.nav-item').addClass('menu-is-opening menu-open');



    })
</script>

<!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

<!-- Bootstrap -->
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<!-- overlayScrollbars -->
<script src="~/js/jquery.overlayScrollbars.min.js"></script>

<!-- AdminLTE App -->
<script src="~/js/adminlte.js"></script>

<!-- PAGE PLUGINS -->

<!-- jQuery Mapael -->
<script src="~/js/jquery.mousewheel.js"></script>
<script src="~/js/raphael.min.js"></script>
<script src="~/js/jquery.mapael.min.js"></script>

<!-- ChartJS -->
<script src="~/js/Chart.js"></script>
<!--DataTableJS-->
<script src="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.js"></script>
<script src="~/datatable/datatables.min.js"></script>
<script src="~/js/datatable.file.js"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

Project.MVCUI/Areas/SuperAdmin/Views/User/Index.cshtml
@using Project.Entities.Models;
@model List<User>;

<style>
    body {
        padding: 30px;
    }
</style>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Kullanıcı Görevleri</h3>
                    <a asp-area="SuperAdmin" asp-controller="Role" asp-action="Create" class="btn btn-primary" style="float: right;">Yeni Kullanıcı Oluştur</a>
                </div>
                <div class="card-body table-responsive p-0">
                    <table class="table-bordered" id="dataTableData">
                        <thead>
                            <tr>
                                <th class="cm-strong">Kullanıcı Adı</th>
                                <th class="cm-strong">Adı Soyadı</th>
                                <th class="cm-strong">E-Mail</th>
                                <th class="cm-strong">Tel. No.</th>
                                <td style="text-align:center;" class="cm-strong">İşlemler</td>
                            </tr>
                        </thead>
                        <tbody>

                            @if (Model.Count > 0)
                            {
                                foreach (var user in Model)
                                {
                                    <tr>
                                        <td>@user.UserName</td>
                                        <td>@user.Name @user.Surname</td>
                                        <td>@user.Email</td>
                                        <td>@user.PhoneNumber</td>
                                        <td style="text-align:center;">
                                            <a asp-area="SuperAdmin" asp-controller="Role" asp-action="Update" asp-route-id="@user.Id" class="btn btn-xs btn-warning">Güncelle</a>
                                            <button class="btn btn-xs btn-danger delete" id="@user.Id" name="@user.Name">Sil</button>
                                        </td>
                                    </tr>
                                }
                            }


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- SweetAlert Delete Button -->
@section scripts{
    <script>
        var name;
        var id;
        $(".delete").on("click", function () {
            id = $(this).attr('id');
            name = $(this).attr('name');
            displayAlert();
        })
        function displayAlert() {
            Swal.fire({
                title: 'Emin Misiniz ?',
                text: `${name} İsimli Kullanıcı Silinecek.`,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Vazgeç',
                confirmButtonText: 'Evet, Sil!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: `/SuperAdmin/Role/Delete/${id}`,
                        type: 'get',
                        success: function (data) {
                            Swal.fire(
                                'Silindi!',
                                'Kullanıcı Kaydı Başarıyla Silindi.',
                                'success'
                            ).then((result) => {
                                if (result.isConfirmed) {
                                    location.reload();
                                }
                            })
                        }
                    })
                }
            })
        }
    </script>

    @if (TempData["SuccessMessage"] != null)
    {
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                Swal.fire({
                    title: 'Oluşturuldu !',
                    text: 'Kullanıcı Kaydı Başarıyla Oluşturuldu !',
                    icon: 'success'
                });
            });
        </script>
    }

    @if (TempData["UpdateMessage"] != null)
    {
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                Swal.fire({
                    title: 'Güncellendi !',
                    text: 'Kullanıcı Kaydı Başarıyla Güncellendi !',
                    icon: 'success'
                });
            });
        </script>
    }
}

Project.MVCUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Project.MVCUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project.MVCUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project.MVCUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project.MVCUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Project.MVCUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>